name: Ashkelon Surf Forecast
version: "2.0.1"
slug: ashkelon_surf_forecast
description: Beautiful surf forecast for Ashkelon beach with Hebrew support and Aguacatec-style interface
url: https://github.com/avielj/ashkelon-surf-report
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
ports:
  "8099/tcp": 8099
ports_description:
  "8099/tcp": Web interface
webui: http://[HOST]:[PORT:8099]
panel_icon: mdi:waves
panel_title: Ashkelon Surf
panel_admin: false
options:
  update_interval: 3600
  timezone: "Asia/Jerusalem"
  show_hebrew: true
  show_chart: true
  debug_mode: false
schema:
  update_interval: "int(300,86400)"
  timezone: "str"
  show_hebrew: "bool"
  show_chart: "bool"
  debug_mode: "bool"
watchdog: "http://localhost:8099/health"
