name: Daily Surf Report

on:
  schedule:
    # Run at 5:00 AM UTC = 7:00 AM GMT+2 (Israel winter time)
    # Note: In summer (GMT+3), this will be 8:00 AM
    - cron: '0 5 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  surf-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run daily surf report
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python daily_surf_report.py
    
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: forecast-data-${{ github.run_number }}
        path: |
          *.json
          *.log
          *.png
        retention-days: 7